fullscreen = false
resolution = [1280, 720]  # px
framerate = 60            # FPS
background_color = "gray" # supported colors https://www.pygame.org/docs/ref/color_list.html

[point]
diameter = 2  # px
color = "red" # supported colors https://www.pygame.org/docs/ref/color_list.html

[line]
thickness = 2   # px
color = "white" # supported colors https://www.pygame.org/docs/ref/color_list.html
